project:
  type: book
  output-dir: docs
  resources:
    - results/

execute:
  echo: false
  cache: true
  message: false
  warning: false

book:
  title: "Guide de rédaction / Flore Québec"
  author: "Flore Québec"
  date: today
  chapters:
    - index.qmd
    - formatage.qmd
    - comptes-rendus.qmd
    - photos.qmd
    - taxons.qmd
    - clés.qmd
    - crédits.qmd
    - contribuer.qmd
    - references.qmd
  navbar:
    right:
      - text: "florequebec.ca"
        href: https://florequebec.ca
      - icon: github
        href: https://github.com/flore.quebec/guide

bibliography: references.bib
lang: fr

language:
  crossref-tbl-title: "Tableau"

format:
  html:
    theme:
      - cosmo
      - brand
    grid:
      body-width: 1000px      # default: 900px
      sidebar-width: 300px    # default: 250px
      margin-width: 300px     # default: 300px (right TOC)      
    fontsize: 1.1em  
    toc-title: "Sections"  
  #pdf:
  #  documentclass: scrreprt



